services:
  piprapay:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./piprapay:/var/www/html
    networks:
      - pipra-net
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db_piprapay
      MARIADB_USER: tamimh
      MARIADB_PASSWORD: lMFxQB8ajhfzVzAv
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - pipra-net

networks:
  pipra-net:

volumes:
  mariadb_data:
# 11111111
